version: '3.9'
services:
  challengeuseraccess:
    image: ${DOCKER_REGISTRY-}challengeuseraccess
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
      - :80
    depends_on:
      - sqldata
    volumes:
      - keyvolume:/root/.aspnet/DataProtection-Keys

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=tjm12345*
      - ACCEPT_EULA=Y
    volumes:
        - T:\ProjetosEstudo\ProjetosC#\SqlDockerData:/var/opt/mssql/data
    ports:
      - "1450:1433"

volumes:
  keyvolume: