version: '3.4'
services:
  sqldata:
    image: postgres:latest
    container_name: sqldata_db
    ports:
    - 2222:5432
    environment:
    - POSTGRES_USERNAME=challenge
    - POSTGRES_PASSWORD=challenge
    - POSTGRES_DATABASE=Employee_Db
    restart: always
    volumes:   
    - keyvolume:/var/lib/postgresql/data

volumes:
  keyvolume: