FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:8000;http://+:80;
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["ChallengeUserAccess.csproj", "./"]
RUN dotnet restore "ChallengeUserAccess.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ChallengeUserAccess.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ChallengeUserAccess.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChallengeUserAccess.dll"]